<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../Discord.Net.targets" />
  <Import Project="../../StyleAnalyzer.targets" />
  <PropertyGroup>
    <AssemblyName>Discord.Net.Core</AssemblyName>
    <RootNamespace>Discord</RootNamespace>
    <Description>The core components for the Discord.Net library.</Description>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net5.0|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net5.0|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Collections.Immutable" Version="7.0.0" />
    <PackageReference Include="System.Interactive.Async" Version="6.0.1" />
    <PackageReference Include="IDisposableAnalyzers" Version="4.0.6">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
